server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service    #路由表示 唯一标识
          uri: lb://userservice
          predicates: #路由断言 判断请求是否符合规则
            - Path=/user/**   #路径断言  判断路径是否以/user开头,如果是则符合
          #加入过滤器
          filters:
        #            - AddRequestHeader=Truth,Itcast is freaking aowsome! #添加请求头参数
        - id:  order-service
          uri: lb://orderservice
          predicates: #路由断言 判断请求是否符合规则
            - Path=/order/**   #路径断言  判断路径是否以/user开头,如果是则符合
            - Before=2023-04-13T15:14:47.443+08:00[Asia/Shanghai]
      #        全局配置
      default-filters:
        - AddRequestHeader=Truth, Itast is freaking awesome !
      # 全局跨域配置
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
